version: "3.3"
services:
  quarkus:
    container_name: quarkus
    build:
      context: ./labseq-quarkus/src/main/docker/Dockerfile.jvm
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  angular:
    container_name: angular
    build:
      context: ./labseq-angular
      dockerfile: Dockerfile
    ports:
      - "4042:4042"