version: "3.3"
services:
  quarkus:
    image: paketobuildpacks/quarkus
    container_name: quarkus
    build:
      context: .\labseq-quarkus\src\main\docker
      dockerfile: Dockerfile.jvm
    ports:
      - "8080:8080"